### ISSUE TITLE
release-clm5.0.30 merging  with ctsm1.0.dev093 prior to fates_next_api merge

### ISSUE THREAD

**Issue by glemieux** [glemieux/ctsm#1]
Creating this issue as a place to discuss issues with merging [release-clm5.0.30](https://github.com/ESCOMP/CTSM/tree/release-clm5.0.30) and [ctsm1.0.dev093](https://github.com/ESCOMP/CTSM/tree/ctsm1.0.dev093) as noted here: 
https://github.com/ESCOMP/CTSM/issues/1008#issuecomment-632272794

Deconflicting branch is https://github.com/glemieux/ctsm/tree/release-clm5.0.30-ctsm1.0.dev093

**Comment by glemieux** [comment]
@ekluzek doing a diff on the two branches I notice that [bld/configure](https://github.com/ESCOMP/CTSM/blob/release-clm5.0.30/bld/configure) is not included in the dev093 tag on master.  Did this code get renamed or moved elsewhere?

**Comment by ekluzek** [comment]
It was removed on master and is unneeded.

**Comment by glemieux** [comment]
@ekluzek the following exists in the release branch version of the code.  Should it be included in the merge up to ctsm1.0.dev093?  Note I have not corrected the change from `waterflux_inst%` to `water_inst%waterfluxbulk_inst%` yet:
https://github.com/glemieux/ctsm/blob/8ac9d0b2207b7de7eb7a1a21e19c6b8c390c8b68/src/main/lnd2atmMod.F90#L364-L371

The commit for this code is: https://github.com/ESCOMP/ctsm/commit/71b3a0a93d174ff13e888d7638c0729fdc8936d8

**Comment by ekluzek** [comment]
glacier_region_rain_to_snow_behavior was something that was JUST put on the release branch. So we should remove it in this update of fates_next_api, so that fates_next_api will be like what's on master.

**Comment by glemieux** [comment]
> glacier_region_rain_to_snow_behavior was something that was JUST put on the release branch. So we should remove it in this update of fates_next_api, so that fates_next_api will be like what's on master

Does that mean that everything in the above commit should be reverted:  https://github.com/ESCOMP/ctsm/commit/71b3a0a93d174ff13e888d7638c0729fdc8936d8?  Including things like `rain_to_snow_runoff`?

**Comment by ekluzek** [comment]
> Does that mean that everything in the above commit should be removed: [ESCOMP@71b3a0a](https://github.com/ESCOMP/CTSM/commit/71b3a0a93d174ff13e888d7638c0729fdc8936d8)?

Yes. 

release-clm5.0.15 was skipped on master (the above commit you point to). I don't see anything else that's like that (there was a cime update that doesn't apply for master in release-clm5.0.19, but nothing like this other commit)

**Comment by glemieux** [comment]
This branch passes regression test comparisons using `clm_short` now.  Results are here:
```
/glade/u/home/glemieux/scratch/ctsm-tests/tests_ctsmdev-release-merge
```

**Comment by glemieux** [comment]
Tested this branch last weekend with full `aux_clm` regression suite: 
```
/glade/u/home/glemieux/scratch/ctsm-tests/tests_ctsmdev-release-merge-fullregression
```
I'm getting the following DIFF fails:
```
    FAIL ERP_P36x2_Lm13.f10_f10_musgs.IHistClm50Bgc.cheyenne_gnu.clm-monthly BASELINE ctsm1.0.dev093: DIFF
    FAIL ERS_Ly3_Mmpi-serial.1x1_smallvilleIA.IHistClm50BgcCropQianGs.cheyenne_gnu.clm-cropMonthOutput BASELINE ctsm1.0.dev093: DIFF
    FAIL SMS_Ly1_Mmpi-serial.1x1_brazil.IHistClm50BgcQianGs.cheyenne_gnu.clm-output_bgc_highfreq BASELINE ctsm1.0.dev093: DIFF
    FAIL ERP_D_Ld3.f09_g17.I2000Clm50SpGs.cheyenne_intel.clm-prescribed BASELINE ctsm1.0.dev093: DIFF
    FAIL ERP_D_Ld5.f10_f10_musgs.IHistClm50BgcCrop.cheyenne_intel.clm-allActive BASELINE ctsm1.0.dev093: DIFF
    FAIL ERP_Ly3_P72x2.f10_f10_musgs.IHistClm50BgcCrop.cheyenne_intel.clm-cropMonthOutput BASELINE ctsm1.0.dev093: DIFF
    FAIL ERP_P36x2_Lm13.f10_f10_musgs.IHistClm50Bgc.cheyenne_intel.clm-monthly BASELINE ctsm1.0.dev093: DIFF
    FAIL ERS_Ly3_P72x2.f10_f10_musgs.IHistClm50BgcCropG.cheyenne_intel.clm-cropMonthOutput BASELINE ctsm1.0.dev093: DIFF
    FAIL ERS_Ly5_P144x1.f10_f10_musgs.IHistClm50BgcCrop.cheyenne_intel.clm-cropMonthOutput BASELINE ctsm1.0.dev093: DIFF
    FAIL ERS_Ly5_P72x1.f10_f10_musgs.IHistClm45BgcCrop.cheyenne_intel.clm-cropMonthOutput BASELINE ctsm1.0.dev093: DIFF
    FAIL ERS_Ly6_Mmpi-serial.1x1_smallvilleIA.IHistClm50BgcCropQianGs.cheyenne_intel.clm-cropMonthOutput BASELINE ctsm1.0.dev093: DIFF
    FAIL LCISO_Lm13.f10_f10_musgs.IHistClm50BgcCrop.cheyenne_intel.clm-ciso_monthly BASELINE ctsm1.0.dev093: DIFF
    FAIL SMS_D_Ly6_Mmpi-serial.1x1_smallvilleIA.IHistClm45BgcCropQianGs.cheyenne_intel.clm-cropMonthOutput BASELINE ctsm1.0.dev093: DIFF
```
Note that all the DIFF failures, except one, are for the compsets `IHistClm` all of which also failed NLCOMP.  All NLCOMP failure are for this compset timeframe as well, although note that not all NLCOMP failures resulted in a DIFF failure (i.e. some PASSED baseline check).

All but one of the `IHistClm` DIFF failures is a `BgcCrop` compset.  This reminded me that there was an unresolved difference in the namelist_ctsm_default.xml that might be related?  In the ctsm1.0.dev093 baseline the following lines have `irrigate=.false`:

clm4.5:
https://github.com/glemieux/ctsm/blob/ce3bab4f1d673eeae7821cd32cfa6f763ffcd2c7/bld/namelist_files/namelist_defaults_ctsm.xml#L532-L534
clm5.0:
https://github.com/glemieux/ctsm/blob/ce3bab4f1d673eeae7821cd32cfa6f763ffcd2c7/bld/namelist_files/namelist_defaults_ctsm.xml#L554-L556
https://github.com/glemieux/ctsm/blob/ce3bab4f1d673eeae7821cd32cfa6f763ffcd2c7/bld/namelist_files/namelist_defaults_ctsm.xml#L615-L620

I'm going to locally edit the namelist file and see if this clears that subset of DIFF errors.

UPDATE: running with the local edit to irrigation in the namelist file result in the same DIFF errors.  Did result in a new, unexpected RUN fail though.  Suggests to me that irrigation difference is fine.

**Comment by glemieux** [comment]
Still waiting on the `irrigate=.false.` test check to run.  I went and looked at the NLCOMP failures to see what was being reported in TestStatus.log.  @ekluzek I'm seeing the following NLCOMP difference in the above list of DIFF fails that also have NLCOMP differences:
```
    Differences in namelist 'ndepdyn_nml':
    BASE: ndep_taxmode = 'cycle'
    COMP: ndep_taxmode = 'extend'
    BASE: stream_year_last_ndep = 2005
    COMP: stream_year_last_ndep = 2015
```
I'm not familiar with where the `ndepdyn_nml` contents get set.  Do you think this update is acceptable?

UPDATE: I see it being initialized with `extend` via `ndep_init` in ndepStreamMod.F90 and some settings in user_default_ctsm.xml, but they match the ctsm1.0.dev093, so I'm guessing this is happening somewhere else that I'm not seeing.

I should note that the following only have the difference in `ndep_taxmode` and not a difference in `stream_year_last_ndep`:
```
ERS_Ly5_P72x1.f10_f10_musgs.IHistClm45BgcCrop.cheyenne_intel.clm-cropMonthOutput
SMS_D_Ly6_Mmpi-serial.1x1_smallvilleIA.IHistClm45BgcCropQianGs.cheyenne_intel.clm-cropMonthOutput
```

**Comment by glemieux** [comment]
Closing issue as the update has been complete via rebase.
